name: jampa_trip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/planeta.png
    - lib/assets/images/coqueirinho.jpeg
    - lib/assets/images/letreiro.jpeg
    - lib/assets/images/centrojoaopessoa.jpeg
    - lib/assets/images/tambaba.jpeg
    - lib/assets/images/piscinasnaturais.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: lib\assets\fonts\Poppins-Regular.ttf
        - asset: lib\assets\fonts\Poppins-Bold.ttf
          weight: 700
