name: jampa_trip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  jwt_decode: ^0.3.1
  intl: ^0.18.1
  image_picker: ^1.1.2
  flutter_multi_formatter: ^2.0.1
  flutter_time_picker_spinner: ^2.0.0
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/planeta.png
    - lib/assets/images/coqueirinho.jpeg
    - lib/assets/images/letreiro.jpeg
    - lib/assets/images/centrojoaopessoa.jpeg
    - lib/assets/images/tambaba.jpeg
    - lib/assets/images/piscinasnaturais.jpeg
    - lib/assets/images/profile.png
    - lib/assets/images/pix.png
    - lib/assets/images/cartao.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: lib\assets\fonts\Poppins-Regular.ttf
        - asset: lib\assets\fonts\Poppins-Bold.ttf
          weight: 700
